// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: TeeRpcService.proto

package tee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxStatusCode int32

const (
	TxStatusCode_SUCCESS           TxStatusCode = 0
	TxStatusCode_EXEC_FAIL         TxStatusCode = 1
	TxStatusCode_PARTLY_EXEC_ERROR TxStatusCode = 2
	TxStatusCode_TIMEOUT           TxStatusCode = 3
	TxStatusCode_INVALID_PARAMETER TxStatusCode = 4
	TxStatusCode_NO_PERMISSION     TxStatusCode = 5
	TxStatusCode_INTERNAL_ERROR    TxStatusCode = 6
)

// Enum value maps for TxStatusCode.
var (
	TxStatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "EXEC_FAIL",
		2: "PARTLY_EXEC_ERROR",
		3: "TIMEOUT",
		4: "INVALID_PARAMETER",
		5: "NO_PERMISSION",
		6: "INTERNAL_ERROR",
	}
	TxStatusCode_value = map[string]int32{
		"SUCCESS":           0,
		"EXEC_FAIL":         1,
		"PARTLY_EXEC_ERROR": 2,
		"TIMEOUT":           3,
		"INVALID_PARAMETER": 4,
		"NO_PERMISSION":     5,
		"INTERNAL_ERROR":    6,
	}
)

func (x TxStatusCode) Enum() *TxStatusCode {
	p := new(TxStatusCode)
	*p = x
	return p
}

func (x TxStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_TeeRpcService_proto_enumTypes[0].Descriptor()
}

func (TxStatusCode) Type() protoreflect.EnumType {
	return &file_TeeRpcService_proto_enumTypes[0]
}

func (x TxStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxStatusCode.Descriptor instead.
func (TxStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_TeeRpcService_proto_rawDescGZIP(), []int{0}
}

type TeeTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// header of the request
	Header *TeeTxHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// payload of the request, can be unmarshalled according to tx_type in header
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// signature of [header bytes || payload bytes]
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TeeTxRequest) Reset() {
	*x = TeeTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TeeRpcService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeeTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeeTxRequest) ProtoMessage() {}

func (x *TeeTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TeeRpcService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeeTxRequest.ProtoReflect.Descriptor instead.
func (*TeeTxRequest) Descriptor() ([]byte, []int) {
	return file_TeeRpcService_proto_rawDescGZIP(), []int{0}
}

func (x *TeeTxRequest) GetHeader() *TeeTxHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TeeTxRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TeeTxRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TeeTxHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// transaction id set by sender, should be unique
	BusiId string `protobuf:"bytes,1,opt,name=busi_id,json=busiId,proto3" json:"busi_id,omitempty"`
	// transaction txid
	TxId string `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// transaction timestamp, in unix timestamp format, seconds
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeeTxHeader) Reset() {
	*x = TeeTxHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TeeRpcService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeeTxHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeeTxHeader) ProtoMessage() {}

func (x *TeeTxHeader) ProtoReflect() protoreflect.Message {
	mi := &file_TeeRpcService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeeTxHeader.ProtoReflect.Descriptor instead.
func (*TeeTxHeader) Descriptor() ([]byte, []int) {
	return file_TeeRpcService_proto_rawDescGZIP(), []int{1}
}

func (x *TeeTxHeader) GetBusiId() string {
	if x != nil {
		return x.BusiId
	}
	return ""
}

func (x *TeeTxHeader) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TeeTxHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TeeTransactPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// encrypto data
	Edata [][]byte `protobuf:"bytes,1,rep,name=edata,proto3" json:"edata,omitempty"`
}

func (x *TeeTransactPayload) Reset() {
	*x = TeeTransactPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TeeRpcService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeeTransactPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeeTransactPayload) ProtoMessage() {}

func (x *TeeTransactPayload) ProtoReflect() protoreflect.Message {
	mi := &file_TeeRpcService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeeTransactPayload.ProtoReflect.Descriptor instead.
func (*TeeTransactPayload) Descriptor() ([]byte, []int) {
	return file_TeeRpcService_proto_rawDescGZIP(), []int{2}
}

func (x *TeeTransactPayload) GetEdata() [][]byte {
	if x != nil {
		return x.Edata
	}
	return nil
}

type TeeTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusiId string `protobuf:"bytes,1,opt,name=busi_id,json=busiId,proto3" json:"busi_id,omitempty"`
	TxId   string `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// response code
	Code TxStatusCode `protobuf:"varint,3,opt,name=code,proto3,enum=traffic.tee.TxStatusCode" json:"code,omitempty"`
	// response message
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TeeTxResponse) Reset() {
	*x = TeeTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TeeRpcService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeeTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeeTxResponse) ProtoMessage() {}

func (x *TeeTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TeeRpcService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeeTxResponse.ProtoReflect.Descriptor instead.
func (*TeeTxResponse) Descriptor() ([]byte, []int) {
	return file_TeeRpcService_proto_rawDescGZIP(), []int{3}
}

func (x *TeeTxResponse) GetBusiId() string {
	if x != nil {
		return x.BusiId
	}
	return ""
}

func (x *TeeTxResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TeeTxResponse) GetCode() TxStatusCode {
	if x != nil {
		return x.Code
	}
	return TxStatusCode_SUCCESS
}

func (x *TeeTxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_TeeRpcService_proto protoreflect.FileDescriptor

var file_TeeRpcService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x54, 0x65, 0x65, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x74,
	0x65, 0x65, 0x22, 0x78, 0x0a, 0x0c, 0x54, 0x65, 0x65, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x74, 0x65, 0x65,
	0x2e, 0x54, 0x65, 0x65, 0x54, 0x78, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x59, 0x0a, 0x0b,
	0x54, 0x65, 0x65, 0x54, 0x78, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x62,
	0x75, 0x73, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75,
	0x73, 0x69, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2a, 0x0a, 0x12, 0x54, 0x65, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x0d, 0x54, 0x65, 0x65, 0x54, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75, 0x73, 0x69, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x73, 0x69, 0x49, 0x64, 0x12, 0x13,
	0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x78, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x74, 0x65, 0x65, 0x2e,
	0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x8c, 0x01, 0x0a,
	0x0c, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x58,
	0x45, 0x43, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x41, 0x52,
	0x54, 0x4c, 0x59, 0x5f, 0x45, 0x58, 0x45, 0x43, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x12, 0x15, 0x0a,
	0x11, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54,
	0x45, 0x52, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49,
	0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x06, 0x32, 0x60, 0x0a, 0x0d, 0x54,
	0x65, 0x65, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x14,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x65, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x74,
	0x65, 0x65, 0x2e, 0x54, 0x65, 0x65, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x74, 0x65, 0x65, 0x2e, 0x54, 0x65,
	0x65, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x65, 0x6d,
	0x61, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x71, 0x68, 0x79, 0x77, 0x39, 0x39, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2f, 0x74, 0x65,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TeeRpcService_proto_rawDescOnce sync.Once
	file_TeeRpcService_proto_rawDescData = file_TeeRpcService_proto_rawDesc
)

func file_TeeRpcService_proto_rawDescGZIP() []byte {
	file_TeeRpcService_proto_rawDescOnce.Do(func() {
		file_TeeRpcService_proto_rawDescData = protoimpl.X.CompressGZIP(file_TeeRpcService_proto_rawDescData)
	})
	return file_TeeRpcService_proto_rawDescData
}

var file_TeeRpcService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TeeRpcService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_TeeRpcService_proto_goTypes = []interface{}{
	(TxStatusCode)(0),          // 0: traffic.tee.TxStatusCode
	(*TeeTxRequest)(nil),       // 1: traffic.tee.TeeTxRequest
	(*TeeTxHeader)(nil),        // 2: traffic.tee.TeeTxHeader
	(*TeeTransactPayload)(nil), // 3: traffic.tee.TeeTransactPayload
	(*TeeTxResponse)(nil),      // 4: traffic.tee.TeeTxResponse
}
var file_TeeRpcService_proto_depIdxs = []int32{
	2, // 0: traffic.tee.TeeTxRequest.header:type_name -> traffic.tee.TeeTxHeader
	0, // 1: traffic.tee.TeeTxResponse.code:type_name -> traffic.tee.TxStatusCode
	1, // 2: traffic.tee.TeeRpcService.SendRemoteTeeRequest:input_type -> traffic.tee.TeeTxRequest
	4, // 3: traffic.tee.TeeRpcService.SendRemoteTeeRequest:output_type -> traffic.tee.TeeTxResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TeeRpcService_proto_init() }
func file_TeeRpcService_proto_init() {
	if File_TeeRpcService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TeeRpcService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeeTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TeeRpcService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeeTxHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TeeRpcService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeeTransactPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TeeRpcService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeeTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TeeRpcService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TeeRpcService_proto_goTypes,
		DependencyIndexes: file_TeeRpcService_proto_depIdxs,
		EnumInfos:         file_TeeRpcService_proto_enumTypes,
		MessageInfos:      file_TeeRpcService_proto_msgTypes,
	}.Build()
	File_TeeRpcService_proto = out.File
	file_TeeRpcService_proto_rawDesc = nil
	file_TeeRpcService_proto_goTypes = nil
	file_TeeRpcService_proto_depIdxs = nil
}
